- name: remove php-xcache
  yum:
    name: php-xcache
    state: absent

- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo remirepo
    file: external_repos
    baseurl: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Install php
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - php
    - php-mcrypt
    - php-cli
    - php-gd
    - php-curl
    - php-mysql
    - php-ldap
    - php-zip
    - php-fileinfo
    - php-xml
    - php-fpm
    - php-mbstring
    #- php-json
    #- php-mcrypt
    #- php-soap
    #- php-xmlrpc
