- name: remove php-xcache
  yum:
    name: php-xcache
    state: absent

- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo remirepo
    baseurl: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: php74
  package::
    name: "{{ item }}"
    state: present
  loop:
    - php
    - php-xml
    - php-mcrypt
    - php-cli
    - php-curl
    - php-ldap
    - php-soap
    - php-xmlrpc
    - php-mbstring
    - php-json
    - php-gd
    - php-zip
    - php-fileinfo
    - php-mcrypt
    - php-mysql
    - php74-php-intl
    - php-fpm
  ignore_errors: true
