    #- name: stop mariadb
    #  service:
    #    name: mariadb
    #    state: stopped

    #- name: Synchronization origin database config and FS config
      #become: yes
    #  synchronize:
    #    src: /var/lib/mysql
    #    dest: /appli/projects/wikib/mariadb/mysql
    #    perms: yes
        #recursive: yes

- name: Synchronization origin database config and FS config
  command: rsync -av /var/lib/mysql /appli/projects/wikib/mariadb
  register: result
  when: result is failed



- name: Rename mysql en mysql.bak
  copy: remote_src=True src=/var/lib/mysql dest=/var/lib/mysql.bak
  when: result is succeeded

- name: delete /var/lib/mysql
  file:
    path: /var/lib/mysql
    state: absent


- name: Create mariadb my.cnf
  template:
    src: roles/config_mariadb/templates/new_maria_my.cnf.j2
    dest: /etc/my.cnf
  notify: restart mariadb

#- name: Synchronization origin database config and FS config
#  command: ln -s /appli/projects/wikib/mariadb/mysql /var/lib/mysql

- name: Create symlink for database old new
  file:
    path: /appli/projects/wikib/mariadb/mysql
    dest: /var/lib/mysql
    state: link
    force: yes
    #notify: mariadb reload
