    #- name: remove mariadb-server
    #  yum:
    #    name:
    #      - mariadb-server
    #    state: absent

- name: Install Mariadb
  package:
    name: "{{ item }}"
    state: present
  loop:
    - mariadb-server
    - MySQL-python

- name: start mariadb
  service:
    name: mariadb
    state: started


#- file:
#    path: /var/lib/mysql/mysql.sock
#    owner: mysql
#    group: mysql
#    mode: 0755
