    #- name: remove mariadb-server
    #  yum:
    #    name:
    #      - mariadb-server
    #    state: absent

      - name: install mariadb-server
        yum:
          name:
            - mariadb-server
          state: present
