    - name: install Mariadb
      yum:
        name:
          - mariadb-server
        state: present

    - name: remove Mariadb
      yum:
        name:
          - mariadb-server
        state: absent
